# Generated by Django 4.2.7 on 2024-07-24 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_subscription_stripecustomer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripecustomer',
            old_name='stripeCustomerId',
            new_name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='stripePriceId',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='stripeSubscriptionId',
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='has_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
