# Generated by Django 4.2.7 on 2024-06-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_uploadmodel_downloadmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadmodel',
            name='url',
        ),
        migrations.RemoveField(
            model_name='uploadmodel',
            name='url',
        ),
        migrations.AddField(
            model_name='downloadmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='downloaded_files/'),
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/'),
        ),
    ]
